python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 150 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 375 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 15 --hidden_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 45 --hidden_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 90 --hidden_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 150 --hidden_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 375 --hidden_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 15 --hidden_dims 1024 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 45 --hidden_dims 1024 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 90 --hidden_dims 1024 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 150 --hidden_dims 1024 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 375 --hidden_dims 1024 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gcn_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 15 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 45 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 90 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 150 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 375 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 15 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 45 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 90 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 150 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 375 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 15 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-computers_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 45 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-computers_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 90 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-computers_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 150 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 375 --hidden_dims 256 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 15 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 45 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 90 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 150 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 375 --hidden_dims 512 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 15 --hidden_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 45 --hidden_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 90 --hidden_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 150 --hidden_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 375 --hidden_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_ggnn_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 128 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 8 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 8 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 8 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 8 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 8 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 256 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 256 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 256 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 256 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 256 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 128 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gat_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 15 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 45 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 90 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 150 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 375 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 15 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 45 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 90 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 150 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 375 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 15 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-computers_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 45 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-computers_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 90 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-computers_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 150 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 375 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 --fix_time 1400 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 15 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 45 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 90 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 150 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 375 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 --fix_time 1000 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 15 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 45 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 90 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 150 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_time.py --epochs 10000 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 375 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 --fix_time 1750 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp6_sampling_acc/batch_acc_cum_fix_time/cluster_gaan_flickr_375.log 2>&1
