python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gcn --data amazon-photo --device cuda:1 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gcn_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gcn --data pubmed --device cuda:1 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gcn_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gcn --data amazon-computers --device cuda:1 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gcn_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gcn --data coauthor-physics --device cuda:1 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gcn_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gcn --data flickr --device cuda:1 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gcn_flickr_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_ggnn_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model ggnn --data pubmed --device cuda:1 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_ggnn_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_ggnn_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_ggnn_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model ggnn --data flickr --device cuda:1 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_ggnn_flickr_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gat --data amazon-photo --device cuda:1 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gat_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gat --data pubmed --device cuda:1 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gat_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gat --data amazon-computers --device cuda:1 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gat_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gat_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gat --data flickr --device cuda:1 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gat_flickr_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gaan_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gaan --data pubmed --device cuda:1 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gaan_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gaan_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gaan_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_full_batch_acc_cum.py --runs 1 --epochs 1000 --mode graphsage --model gaan --data flickr --device cuda:1 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum/graphsage_gaan_flickr_full.log 2>&1
