python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-photo --device cuda:0 --batch_partitions 15 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-photo --device cuda:0 --batch_partitions 45 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-photo --device cuda:0 --batch_partitions 90 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-photo --device cuda:0 --batch_partitions 150 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-photo --device cuda:0 --batch_partitions 375 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-photo --device cuda:0 --batch_partitions 750 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gcn --data amazon-photo --device cuda:0 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data pubmed --device cuda:0 --batch_partitions 15 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data pubmed --device cuda:0 --batch_partitions 45 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data pubmed --device cuda:0 --batch_partitions 90 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data pubmed --device cuda:0 --batch_partitions 150 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data pubmed --device cuda:0 --batch_partitions 375 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data pubmed --device cuda:0 --batch_partitions 750 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gcn --data pubmed --device cuda:0 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 15 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 45 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 90 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 150 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 375 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data amazon-computers --device cuda:0 --batch_partitions 750 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gcn --data amazon-computers --device cuda:0 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 15 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 45 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 90 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 150 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 375 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --batch_partitions 750 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gcn --data coauthor-physics --device cuda:0 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 15 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 45 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 90 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 150 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 375 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gcn --data flickr --device cuda:0 --batch_partitions 750 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gcn --data flickr --device cuda:0 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gcn_flickr_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 15 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 45 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 90 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 150 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 375 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --batch_partitions 750 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model ggnn --data amazon-photo --device cuda:0 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 15 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 45 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 90 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 150 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 375 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data pubmed --device cuda:0 --batch_partitions 750 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model ggnn --data pubmed --device cuda:0 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 15 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 45 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 90 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 150 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 375 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --batch_partitions 750 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model ggnn --data amazon-computers --device cuda:0 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 15 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 45 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 90 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 150 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 375 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --batch_partitions 750 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model ggnn --data coauthor-physics --device cuda:0 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 15 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 45 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 90 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 150 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 375 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model ggnn --data flickr --device cuda:0 --batch_partitions 750 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model ggnn --data flickr --device cuda:0 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_ggnn_flickr_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-photo --device cuda:0 --batch_partitions 750 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gat --data amazon-photo --device cuda:0 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data pubmed --device cuda:0 --batch_partitions 750 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gat --data pubmed --device cuda:0 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-computers --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-computers --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-computers --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-computers --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-computers --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data amazon-computers --device cuda:0 --batch_partitions 750 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gat --data amazon-computers --device cuda:0 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data coauthor-physics --device cuda:0 --batch_partitions 750 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gat --data coauthor-physics --device cuda:0 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 15 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 45 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 90 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 150 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 375 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gat --data flickr --device cuda:0 --batch_partitions 750 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gat --data flickr --device cuda:0 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gat_flickr_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 15 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 45 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 90 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 150 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 375 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-photo --device cuda:0 --batch_partitions 750 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gaan --data amazon-photo --device cuda:0 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-photo_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 15 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 45 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 90 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 150 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 375 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data pubmed --device cuda:0 --batch_partitions 750 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gaan --data pubmed --device cuda:0 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_pubmed_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 15 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 45 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 90 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 150 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 375 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data amazon-computers --device cuda:0 --batch_partitions 750 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gaan --data amazon-computers --device cuda:0 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_amazon-computers_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 15 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 45 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 90 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 150 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 375 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --batch_partitions 750 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gaan --data coauthor-physics --device cuda:0 --heads 1 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_coauthor-physics_full.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 15 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_15.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 45 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_45.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 90 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_90.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 150 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_150.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 375 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_375.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc.py --runs 1 --epochs 500 --mode cluster --model gaan --data flickr --device cuda:0 --batch_partitions 750 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_750.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main.py --runs 1 --epochs 1000 --mode cluster --model gaan --data flickr --device cuda:0 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc/cluster_gaan_flickr_full.log 2>&1
