python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gcn --data flickr --device cuda:1 --batch_size 8925 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gcn_flickr_8925.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gcn --data flickr --device cuda:1 --batch_size 22313 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gcn_flickr_22313.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gcn --data flickr --device cuda:1 --batch_size 44625 --hidden_dims 1024 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gcn_flickr_44625.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --batch_size 77 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-photo_77.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --batch_size 230 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-photo_230.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --batch_size 459 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-photo_459.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --batch_size 765 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-photo_765.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --batch_size 1913 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-photo_1913.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-photo --device cuda:1 --batch_size 3825 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-photo_3825.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data pubmed --device cuda:1 --batch_size 198 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_pubmed_198.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data pubmed --device cuda:1 --batch_size 592 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_pubmed_592.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data pubmed --device cuda:1 --batch_size 1184 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_pubmed_1184.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data pubmed --device cuda:1 --batch_size 1972 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_pubmed_1972.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data pubmed --device cuda:1 --batch_size 4930 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_pubmed_4930.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data pubmed --device cuda:1 --batch_size 9859 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_pubmed_9859.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --batch_size 138 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-computers_138.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --batch_size 413 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-computers_413.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --batch_size 826 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-computers_826.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --batch_size 1376 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-computers_1376.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --batch_size 3438 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-computers_3438.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data amazon-computers --device cuda:1 --batch_size 6876 --hidden_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_amazon-computers_6876.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --batch_size 345 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_coauthor-physics_345.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --batch_size 1035 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_coauthor-physics_1035.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --batch_size 2070 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_coauthor-physics_2070.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --batch_size 3450 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_coauthor-physics_3450.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --batch_size 8624 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_coauthor-physics_8624.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data coauthor-physics --device cuda:1 --batch_size 17247 --hidden_dims 512 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_coauthor-physics_17247.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data flickr --device cuda:1 --batch_size 893 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_flickr_893.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data flickr --device cuda:1 --batch_size 2678 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_flickr_2678.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data flickr --device cuda:1 --batch_size 5355 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_flickr_5355.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data flickr --device cuda:1 --batch_size 8925 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_flickr_8925.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data flickr --device cuda:1 --batch_size 22313 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_flickr_22313.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model ggnn --data flickr --device cuda:1 --batch_size 44625 --hidden_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_ggnn_flickr_44625.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-photo --device cuda:1 --batch_size 77 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-photo_77.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-photo --device cuda:1 --batch_size 230 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-photo_230.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-photo --device cuda:1 --batch_size 459 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-photo_459.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-photo --device cuda:1 --batch_size 765 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-photo_765.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-photo --device cuda:1 --batch_size 1913 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-photo_1913.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-photo --device cuda:1 --batch_size 3825 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-photo_3825.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data pubmed --device cuda:1 --batch_size 198 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_pubmed_198.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data pubmed --device cuda:1 --batch_size 592 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_pubmed_592.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data pubmed --device cuda:1 --batch_size 1184 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_pubmed_1184.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data pubmed --device cuda:1 --batch_size 1972 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_pubmed_1972.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data pubmed --device cuda:1 --batch_size 4930 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_pubmed_4930.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data pubmed --device cuda:1 --batch_size 9859 --heads 4 --head_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_pubmed_9859.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-computers --device cuda:1 --batch_size 138 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-computers_138.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-computers --device cuda:1 --batch_size 413 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-computers_413.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-computers --device cuda:1 --batch_size 826 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-computers_826.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-computers --device cuda:1 --batch_size 1376 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-computers_1376.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-computers --device cuda:1 --batch_size 3438 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-computers_3438.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data amazon-computers --device cuda:1 --batch_size 6876 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_amazon-computers_6876.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --batch_size 345 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_coauthor-physics_345.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --batch_size 1035 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_coauthor-physics_1035.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --batch_size 2070 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_coauthor-physics_2070.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --batch_size 3450 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_coauthor-physics_3450.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --batch_size 8624 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_coauthor-physics_8624.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data coauthor-physics --device cuda:1 --batch_size 17247 --heads 4 --head_dims 256 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_coauthor-physics_17247.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data flickr --device cuda:1 --batch_size 893 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_flickr_893.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data flickr --device cuda:1 --batch_size 2678 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_flickr_2678.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data flickr --device cuda:1 --batch_size 5355 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_flickr_5355.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data flickr --device cuda:1 --batch_size 8925 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_flickr_8925.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data flickr --device cuda:1 --batch_size 22313 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_flickr_22313.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gat --data flickr --device cuda:1 --batch_size 44625 --heads 4 --head_dims 128 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gat_flickr_44625.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --batch_size 77 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-photo_77.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --batch_size 230 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-photo_230.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --batch_size 459 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-photo_459.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --batch_size 765 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-photo_765.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --batch_size 1913 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-photo_1913.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-photo --device cuda:1 --batch_size 3825 --heads 4 --d_v 8 --d_a 8 --d_m 8 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-photo_3825.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data pubmed --device cuda:1 --batch_size 198 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_pubmed_198.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data pubmed --device cuda:1 --batch_size 592 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_pubmed_592.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data pubmed --device cuda:1 --batch_size 1184 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_pubmed_1184.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data pubmed --device cuda:1 --batch_size 1972 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_pubmed_1972.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data pubmed --device cuda:1 --batch_size 4930 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_pubmed_4930.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data pubmed --device cuda:1 --batch_size 9859 --heads 4 --d_v 2 --d_a 2 --d_m 2 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_pubmed_9859.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --batch_size 138 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-computers_138.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --batch_size 413 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-computers_413.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --batch_size 826 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-computers_826.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --batch_size 1376 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-computers_1376.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --batch_size 3438 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-computers_3438.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data amazon-computers --device cuda:1 --batch_size 6876 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 64 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_amazon-computers_6876.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --batch_size 345 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_coauthor-physics_345.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --batch_size 1035 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_coauthor-physics_1035.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --batch_size 2070 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_coauthor-physics_2070.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --batch_size 3450 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_coauthor-physics_3450.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --batch_size 8624 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_coauthor-physics_8624.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data coauthor-physics --device cuda:1 --batch_size 17247 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 1 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_coauthor-physics_17247.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data flickr --device cuda:1 --batch_size 893 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_flickr_893.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data flickr --device cuda:1 --batch_size 2678 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_flickr_2678.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data flickr --device cuda:1 --batch_size 5355 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_flickr_5355.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data flickr --device cuda:1 --batch_size 8925 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_flickr_8925.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data flickr --device cuda:1 --batch_size 22313 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_flickr_22313.log 2>&1
python -u /home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/main_sampling_batch_acc_cum_fix_epoch.py --epochs 500 --mode graphsage --model gaan --data flickr --device cuda:1 --batch_size 44625 --heads 4 --d_v 32 --d_a 32 --d_m 32 --hidden_dims 8 >>/home/wangzhaokang/wangyunpan/gnns-project/pyg-gnns/paper_exp4_relative_sampling/batch_acc_cum_fix_epoch/graphsage_gaan_flickr_44625.log 2>&1
